//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public string codigo { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public int anioEdicion { get; set; }
        public string genero { get; set; }
        public string editorial { get; set; }
        public System.DateTime fechaIngreso { get; set; }
    }
}
