//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante
    {
        public string codigoLibro { get; set; }
        public string rut { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tipo { get; set; }
        public System.DateTime fechaPrestamo { get; set; }
    }
}
